services:
  - type: web
    name: purofu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    preDeployCommand: flask db upgrade
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromDatabase:
          name: purofu-db
          property: connectionString