"""Add Attendance table

Revision ID: 81497e691622
Revises: 
Create Date: 2025-03-23 19:19:32.898451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81497e691622'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
